# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ariccegho/git/PythonProjects/test3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_dataButton.setGeometry(QtCore.QRect(60, 420, 136, 25))
        self.load_dataButton.setObjectName("load_dataButton")
        self.choose_columns_frame = QtWidgets.QFrame(self.centralwidget)
        self.choose_columns_frame.setGeometry(QtCore.QRect(270, 260, 411, 211))
        self.choose_columns_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_columns_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_columns_frame.setObjectName("choose_columns_frame")
        self.pereEdit = QtWidgets.QLineEdit(self.choose_columns_frame)
        self.pereEdit.setGeometry(QtCore.QRect(230, 110, 131, 25))
        self.pereEdit.setObjectName("pereEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.choose_columns_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 201, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.columns_chooseLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.columns_chooseLayout.setContentsMargins(0, 0, 0, 0)
        self.columns_chooseLayout.setObjectName("columns_chooseLayout")
        self.diapasonButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.diapasonButton.setObjectName("diapasonButton")
        self.columns_chooseLayout.addWidget(self.diapasonButton)
        self.pereButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.pereButton.setObjectName("pereButton")
        self.columns_chooseLayout.addWidget(self.pereButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.choose_columns_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 70, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.fromBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.fromBox.setObjectName("fromBox")
        self.horizontalLayout.addWidget(self.fromBox)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.toBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.toBox.setObjectName("toBox")
        self.horizontalLayout.addWidget(self.toBox)
        self.choose_columnsButton = QtWidgets.QPushButton(self.choose_columns_frame)
        self.choose_columnsButton.setGeometry(QtCore.QRect(260, 150, 131, 25))
        self.choose_columnsButton.setObjectName("choose_columnsButton")
        self.label_3 = QtWidgets.QLabel(self.choose_columns_frame)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 131, 17))
        self.label_3.setObjectName("label_3")
        self.c_sheetBox = QtWidgets.QComboBox(self.choose_columns_frame)
        self.c_sheetBox.setGeometry(QtCore.QRect(70, 40, 86, 25))
        self.c_sheetBox.setObjectName("c_sheetBox")
        self.label_9 = QtWidgets.QLabel(self.choose_columns_frame)
        self.label_9.setGeometry(QtCore.QRect(20, 37, 67, 31))
        self.label_9.setObjectName("label_9")
        self.del_spButton = QtWidgets.QPushButton(self.choose_columns_frame)
        self.del_spButton.setGeometry(QtCore.QRect(20, 150, 231, 25))
        self.del_spButton.setObjectName("del_spButton")
        self.Connection_frame = QtWidgets.QFrame(self.centralwidget)
        self.Connection_frame.setGeometry(QtCore.QRect(10, 10, 671, 131))
        self.Connection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Connection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Connection_frame.setObjectName("Connection_frame")
        self.save_setButton = QtWidgets.QPushButton(self.Connection_frame)
        self.save_setButton.setGeometry(QtCore.QRect(310, 90, 171, 25))
        self.save_setButton.setObjectName("save_setButton")
        self.passLabel = QtWidgets.QLabel(self.Connection_frame)
        self.passLabel.setGeometry(QtCore.QRect(570, 40, 67, 17))
        self.passLabel.setObjectName("passLabel")
        self.unLabel = QtWidgets.QLabel(self.Connection_frame)
        self.unLabel.setGeometry(QtCore.QRect(440, 40, 81, 17))
        self.unLabel.setObjectName("unLabel")
        self.unLine = QtWidgets.QLineEdit(self.Connection_frame)
        self.unLine.setGeometry(QtCore.QRect(420, 60, 113, 25))
        self.unLine.setObjectName("unLine")
        self.load_setButton = QtWidgets.QPushButton(self.Connection_frame)
        self.load_setButton.setGeometry(QtCore.QRect(490, 90, 171, 25))
        self.load_setButton.setObjectName("load_setButton")
        self.dbnLine = QtWidgets.QLineEdit(self.Connection_frame)
        self.dbnLine.setGeometry(QtCore.QRect(300, 60, 113, 25))
        self.dbnLine.setObjectName("dbnLine")
        self.portLabel = QtWidgets.QLabel(self.Connection_frame)
        self.portLabel.setGeometry(QtCore.QRect(220, 40, 67, 17))
        self.portLabel.setObjectName("portLabel")
        self.connectButton = QtWidgets.QPushButton(self.Connection_frame)
        self.connectButton.setGeometry(QtCore.QRect(10, 90, 121, 25))
        self.connectButton.setObjectName("connectButton")
        self.dbnLabel = QtWidgets.QLabel(self.Connection_frame)
        self.dbnLabel.setGeometry(QtCore.QRect(320, 40, 67, 17))
        self.dbnLabel.setObjectName("dbnLabel")
        self.passLine = QtWidgets.QLineEdit(self.Connection_frame)
        self.passLine.setGeometry(QtCore.QRect(540, 60, 121, 25))
        self.passLine.setObjectName("passLine")
        self.hostLabel = QtWidgets.QLabel(self.Connection_frame)
        self.hostLabel.setGeometry(QtCore.QRect(60, 40, 67, 17))
        self.hostLabel.setObjectName("hostLabel")
        self.hostLine = QtWidgets.QLineEdit(self.Connection_frame)
        self.hostLine.setGeometry(QtCore.QRect(10, 60, 191, 25))
        self.hostLine.setObjectName("hostLine")
        self.portLine = QtWidgets.QLineEdit(self.Connection_frame)
        self.portLine.setGeometry(QtCore.QRect(210, 60, 81, 25))
        self.portLine.setObjectName("portLine")
        self.label_4 = QtWidgets.QLabel(self.Connection_frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_4.setObjectName("label_4")
        self.choose_tableBox = QtWidgets.QComboBox(self.Connection_frame)
        self.choose_tableBox.setGeometry(QtCore.QRect(140, 90, 86, 25))
        self.choose_tableBox.setObjectName("choose_tableBox")
        self.edit_frame = QtWidgets.QFrame(self.centralwidget)
        self.edit_frame.setGeometry(QtCore.QRect(10, 260, 251, 141))
        self.edit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_frame.setObjectName("edit_frame")
        self.label_5 = QtWidgets.QLabel(self.edit_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 131, 31))
        self.label_5.setObjectName("label_5")
        self.save_excelButton = QtWidgets.QPushButton(self.edit_frame)
        self.save_excelButton.setGeometry(QtCore.QRect(10, 90, 219, 25))
        self.save_excelButton.setObjectName("save_excelButton")
        self.ofButton = QtWidgets.QPushButton(self.edit_frame)
        self.ofButton.setGeometry(QtCore.QRect(10, 30, 219, 25))
        self.ofButton.setObjectName("ofButton")
        self.status_frame = QtWidgets.QFrame(self.centralwidget)
        self.status_frame.setGeometry(QtCore.QRect(10, 150, 671, 101))
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        self.status_listWidget = QtWidgets.QListWidget(self.status_frame)
        self.status_listWidget.setGeometry(QtCore.QRect(10, 30, 651, 61))
        self.status_listWidget.setObjectName("status_listWidget")
        self.status_label = QtWidgets.QLabel(self.status_frame)
        self.status_label.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.status_label.setObjectName("status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel To PSQL"))
        self.load_dataButton.setText(_translate("MainWindow", "Загрузить данные"))
        self.diapasonButton.setText(_translate("MainWindow", "Диапазон:"))
        self.pereButton.setText(_translate("MainWindow", "Перечисление: n,n1,n2..."))
        self.label.setText(_translate("MainWindow", "C"))
        self.label_2.setText(_translate("MainWindow", "по"))
        self.choose_columnsButton.setText(_translate("MainWindow", "Готово"))
        self.label_3.setText(_translate("MainWindow", "Выбор данных"))
        self.label_9.setText(_translate("MainWindow", "Лист:"))
        self.del_spButton.setText(_translate("MainWindow", "Удалить строки с пробелами"))
        self.save_setButton.setText(_translate("MainWindow", "Сохранить настройки"))
        self.passLabel.setText(_translate("MainWindow", "Password"))
        self.unLabel.setText(_translate("MainWindow", "Username"))
        self.load_setButton.setText(_translate("MainWindow", "Загрузить настройки"))
        self.portLabel.setText(_translate("MainWindow", "Host Port"))
        self.connectButton.setText(_translate("MainWindow", "Подключиться"))
        self.dbnLabel.setText(_translate("MainWindow", "DB Name"))
        self.hostLabel.setText(_translate("MainWindow", "Host IP"))
        self.label_4.setText(_translate("MainWindow", "Подключение"))
        self.label_5.setText(_translate("MainWindow", "Редактирование"))
        self.save_excelButton.setText(_translate("MainWindow", "Сохранить файл"))
        self.ofButton.setText(_translate("MainWindow", "Открыть файл"))
        self.status_label.setText(_translate("MainWindow", "Статус:"))
